---
- hosts: all
  become: true
  tasks:
    - name: install updates Arch
      tags: always
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"
